version: '3'
services:
  db:
    image: postgres:15-alpine
    volumes:
     - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: dfr
      POSTGRES_PASSWORD: dfr
      POSTGRES_DB: dfr
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dfr"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.5-alpine
    expose:
      - 6379
  app:
    build: .
#    volumes:
#      - ./data/app:/app
    env_file:
      - .env
#    environment:
#      STRIPE_API_KEY: "sk_test"
#      EMAIL_USER: "test@test.ru"
#      EMAIL_PASSWORD: "password"
#      CELERY_BROKER_URL: "redis://redis:6379"
#      CELERY_RESULT_BACKEND: "redis://redis:6379"
#      POSTGRES_HOST: db
#      POSTGRES_NAME: dfr
#      POSTGRES_USER: dfr
#      POSTGRES_PASSWORD: dfr
#      POSTGRES_PORT: 5432
    command: >
      bash -c "python manage.py migrate --noinput 
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
