# Generated by Django 4.2.3 on 2023-07-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_subscription_delete_subscrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='owner',
            new_name='subscriber',
        ),
    ]
