# Generated by Django 4.2.3 on 2023-07-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа на stripe'),
        ),
    ]
