# Generated by Django 4.2.3 on 2023-08-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_payments_payment_stripe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
